# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /usr/src/app

# Copy package files
COPY package.json package-lock.json* ./

# Install app dependencies
RUN npm install --ignore-scripts

# Copy the rest of the source code
COPY . .

# Build the project
RUN npm run build

# Expose any required port if needed (optional)
# EXPOSE 3000

# Command to run the server, using environment variables and arguments
# You can override these via docker run -e and command-line arguments
CMD ["node", "build/index.js", "ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", "your_api_key", "your_api_secret", "+123456789"]
